USE [master]
GO

/****** Object:  Table [dbo].[t_pengiriman_craddle]    Script Date: 09/01/2026 13:24:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[t_pengiriman_craddle](
	[idreport] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[jam_berangkat] [datetime] NULL,
	[urut] [nvarchar](50) NULL,
	[no_surat]  AS (concat(format([jam_berangkat],'yyMM')+N'-',format(CONVERT([int],[urut]),'0000'))),
	[no_unit] [nvarchar](50) NULL,
	[km_awal] [float] NULL,
	[customer_1] [nvarchar](100) NULL,
	[jam_tiba_customer_1] [datetime] NULL,
	[jam_dari_customer_1] [datetime] NULL,
	[durasi_jam_customer_1]  AS (CONVERT([varchar](20),dateadd(minute,datediff(minute,[jam_tiba_customer_1],[jam_dari_customer_1]),(0)),(108))),
	[rc_kirim_1_customer_1] [nvarchar](10) NULL,
	[p_kirim_1_customer_1] [float] NULL,
	[rc_ambil_1_customer_1] [nvarchar](10) NULL,
	[p_ambil_1_customer_1] [float] NULL,
	[rc_kirim_2_customer_1] [nvarchar](10) NULL,
	[p_kirim_2_customer_1] [float] NULL,
	[rc_ambil_2_customer_1] [nvarchar](10) NULL,
	[p_ambil_2_customer_1] [float] NULL,
	[rc_kirim_3_customer_1] [nvarchar](10) NULL,
	[p_kirim_3_customer_1] [float] NULL,
	[rc_ambil_3_customer_1] [nvarchar](10) NULL,
	[p_ambil_3_customer_1] [float] NULL,
	[rc_kirim_4_customer_1] [nvarchar](10) NULL,
	[p_kirim_4_customer_1] [float] NULL,
	[rc_ambil_4_customer_1] [nvarchar](10) NULL,
	[p_ambil_4_customer_1] [float] NULL,
	[rc_kirim_5_customer_1] [nvarchar](10) NULL,
	[p_kirim_5_customer_1] [float] NULL,
	[rc_ambil_5_customer_1] [nvarchar](10) NULL,
	[p_ambil_5_customer_1] [float] NULL,
	[corrected_vol_customer_1] [float] NULL,
	[uncorrected_vol_customer_1] [float] NULL,
	[temp_turbin_customer_1] [float] NULL,
	[evc_turbin_customer_1] [float] NULL,
	[km_customer_1] [float] NULL,
	[customer_2] [nvarchar](100) NULL,
	[jam_tiba_customer_2] [datetime] NULL,
	[jam_dari_customer_2] [datetime] NULL,
	[durasi_jam_customer_2]  AS (CONVERT([varchar](20),dateadd(minute,datediff(minute,[jam_tiba_customer_2],[jam_dari_customer_2]),(0)),(108))),
	[rc_kirim_1_customer_2] [nvarchar](10) NULL,
	[p_kirim_1_customer_2] [float] NULL,
	[rc_ambil_1_customer_2] [nvarchar](10) NULL,
	[p_ambil_1_customer_2] [float] NULL,
	[rc_kirim_2_customer_2] [nvarchar](10) NULL,
	[p_kirim_2_customer_2] [float] NULL,
	[rc_ambil_2_customer_2] [nvarchar](10) NULL,
	[p_ambil_2_customer_2] [float] NULL,
	[rc_kirim_3_customer_2] [nvarchar](10) NULL,
	[p_kirim_3_customer_2] [float] NULL,
	[rc_ambil_3_customer_2] [nvarchar](10) NULL,
	[p_ambil_3_customer_2] [float] NULL,
	[rc_kirim_4_customer_2] [nvarchar](10) NULL,
	[p_kirim_4_customer_2] [float] NULL,
	[rc_ambil_4_customer_2] [nvarchar](10) NULL,
	[p_ambil_4_customer_2] [float] NULL,
	[rc_kirim_5_customer_2] [nvarchar](10) NULL,
	[p_kirim_5_customer_2] [float] NULL,
	[rc_ambil_5_customer_2] [nvarchar](10) NULL,
	[p_ambil_5_customer_2] [float] NULL,
	[corrected_vol_customer_2] [float] NULL,
	[uncorrected_vol_customer_2] [float] NULL,
	[temp_turbin_customer_2] [float] NULL,
	[evc_turbin_customer_2] [float] NULL,
	[km_customer_2] [float] NULL,
	[customer_3] [nvarchar](100) NULL,
	[jam_tiba_customer_3] [datetime] NULL,
	[jam_dari_customer_3] [datetime] NULL,
	[durasi_jam_customer_3]  AS (CONVERT([varchar](20),dateadd(minute,datediff(minute,[jam_tiba_customer_3],[jam_dari_customer_3]),(0)),(108))),
	[rc_kirim_1_customer_3] [nvarchar](10) NULL,
	[p_kirim_1_customer_3] [float] NULL,
	[rc_ambil_1_customer_3] [nvarchar](10) NULL,
	[p_ambil_1_customer_3] [float] NULL,
	[rc_kirim_2_customer_3] [nvarchar](10) NULL,
	[p_kirim_2_customer_3] [float] NULL,
	[rc_ambil_2_customer_3] [nvarchar](10) NULL,
	[p_ambil_2_customer_3] [float] NULL,
	[rc_kirim_3_customer_3] [nvarchar](10) NULL,
	[p_kirim_3_customer_3] [float] NULL,
	[rc_ambil_3_customer_3] [nvarchar](10) NULL,
	[p_ambil_3_customer_3] [float] NULL,
	[rc_kirim_4_customer_3] [nvarchar](10) NULL,
	[p_kirim_4_customer_3] [float] NULL,
	[rc_ambil_4_customer_3] [nvarchar](10) NULL,
	[p_ambil_4_customer_3] [float] NULL,
	[rc_kirim_5_customer_3] [nvarchar](10) NULL,
	[p_kirim_5_customer_3] [float] NULL,
	[rc_ambil_5_customer_3] [nvarchar](10) NULL,
	[p_ambil_5_customer_3] [float] NULL,
	[corrected_vol_customer_3] [float] NULL,
	[uncorrected_vol_customer_3] [float] NULL,
	[temp_turbin_customer_3] [float] NULL,
	[evc_turbin_customer_3] [float] NULL,
	[km_customer_3] [float] NULL,
	[jam_tiba_plant] [datetime] NULL,
	[durasi_jam]  AS (CONVERT([varchar](20),dateadd(hour,datediff(hour,[jam_berangkat],[jam_tiba_plant]),(0)),(108))),
	[km_akhir] [float] NULL,
	[Tol_Parkir] [float] NULL,
	[dispatcher] [nvarchar](50) NULL,
	[driver] [nvarchar](50) NULL,
	[asisten] [nvarchar](50) NULL,
	[keterangan] [nvarchar](200) NULL,
	[status] [smallint] NULL,
	[token] [nvarchar](50) NULL,
 CONSTRAINT [PK_t_pengiriman_craddle] PRIMARY KEY CLUSTERED 
(
	[idreport] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[t_pengiriman_craddle] ADD  CONSTRAINT [DF_t_pengiriman_craddle_urut]  DEFAULT (N''+CONVERT([nvarchar](10),NEXT VALUE FOR [dbo].[ticket_t_craddle])) FOR [urut]
GO


